spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

